<?php
/**
 * @file
 * Code for the Adsw Dash feature.
 */

include_once 'adsw_dash.features.inc';

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function adsw_dash_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implementation of hook_theme().
 */
function dfmp_page_theme() {
  return array(
    'dfmp_page_header' => array(
      'template' => 'dfmp_page_header',
      'path' => drupal_get_path('module', 'dfmp_page') . '/theme',
    ),
    'dfmp_homepage_subheader' => array(
      'template' => 'dfmp_homepage_subheader',
      'path' => drupal_get_path('module', 'dfmp_page') . '/theme',
    ),
  );
}
