<?php
/**
 * @file
 * Code for the Adsw Dash feature.
 */

include_once 'adsw_dash.features.inc';

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function adsw_dash_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implementation of hook_theme().
 */
function adsw_dash_theme() {
  return array(
    'adsw_dash_layout' => array(
      'template' => 'adsw_dash_layout',
      'path' => drupal_get_path('module', 'adsw_dash') . '/theme',
    ),
    'adsw_dash_page_content' => array(
      'template' => 'adsw_dash_page_content',
      'path' => drupal_get_path('module', 'adsw_dash') . '/theme',
    ),
    'adsw_dash_page_stat' => array(
      'template' => 'adsw_dash_page_stat',
      'path' => drupal_get_path('module', 'adsw_dash') . '/theme',
    ),
  );
}



function adsw_dash_get_today_impress($date = REQUEST_TIME) {
  $query = db_query("SELECT sum(`impress`) as sum FROM `ad_stat` WHERE `date`='" . date('Y-m-d', $date) . "'");
  $res = $query->fetchAssoc();
  return $res['sum'];
}

function adsw_dash_get_today_clicks($date = REQUEST_TIME) {
  $query = db_query("SELECT sum(`clicks`) as sum FROM `ad_stat` WHERE `date`='" . date('Y-m-d', $date) . "'");
  $res = $query->fetchAssoc();
  return $res['sum'];
}

function adsw_dash_get_today_revenue($date = REQUEST_TIME) {
  $query = db_query("SELECT sum(`earning`) as sum FROM `ad_stat` WHERE `date`='" . date('Y-m-d', $date) . "'");
  $res = $query->fetchAssoc();
  return $res['sum'];
}

function adsw_dash_get_by_days($from = NULL, $to = NULL) {
  global $user;
  if (is_null($from)) {
    $from = date('Y-m-d', strtotime("-1 week +1 day"));
  }
  if (is_null($to)) {
    $to = date('Y-m-d', REQUEST_TIME);
  }

  $query = db_select('ad_stat', 'stat');
  $query->fields('stat', array('date'));
  $query->addExpression('sum(clicks)', 'click');
  $query->addExpression('sum(impress)', 'impress');
  $query->addExpression('avg(ctr)', 'ctr');
  $query->addExpression('avg(cpm)', 'cpm');
  $query->addExpression('sum(earning)', 'earning');
  $query->condition('date', array($from, $to), 'BETWEEN');
  if (isset($_GET['country']) && $_GET['country'] != 'all') {
    $query->condition('stat.country', $_GET['country']);
  }
  $query->condition('user_id', $user->uid);
  $query->groupBy('date');
  $query->orderBy('date', 'ASC');
  $res = $query->execute()->fetchAll();

  $data = array();
  $current = $from;
  while (strtotime($current) <= strtotime($to)) {
    $data[$current] = new stdClass;
    $data[$current]->date = $current;
    $data[$current]->click = 0;
    $data[$current]->impress = 0;
    $data[$current]->ctr = 0;
    $data[$current]->cpm = 0;
    $data[$current]->earning = 0;
    foreach($res as $val) {
      if ($val->date == $current) {
        $data[$current] = $val;
        break;
      }
    }
    $current = date('Y-m-d', strtotime('+1 day', strtotime($current)));
  }

  return $data;
}

function adsw_dash_get_by_countries($from = NULL, $to = NULL) {
  global $user;

  if (is_null($from)) {
    $from = date('Y-m-d', strtotime("-1 week +1 day"));
  }
  if (is_null($to)) {
    $to = date('Y-m-d', REQUEST_TIME);
  }
  $countries = country_get_list();
  $query = db_query("SELECT country, sum(clicks) as click, sum(impress) as impress, avg(ctr) as ctr, avg(cpm) as cpm, sum(earning) as earning FROM `ad_stat` WHERE date BETWEEN '" . $from . "' AND '" . $to . "' GROUP BY `country` ORDER BY `country` ASC");
  $res = $query->fetchAll();

  $query = db_select('ad_stat', 'stat');
  $query->fields('stat', array('country'));
  $query->addExpression('sum(clicks)', 'click');
  $query->addExpression('sum(impress)', 'impress');
  $query->addExpression('avg(ctr)', 'ctr');
  $query->addExpression('avg(cpm)', 'cpm');
  $query->addExpression('sum(earning)', 'earning');
  $query->condition('date', array($from, $to), 'BETWEEN');
  if (isset($_GET['country']) && $_GET['country'] != 'all') {
    $query->condition('stat.country', $_GET['country']);
  }
  $query->condition('user_id', $user->uid);
  $query->groupBy('country');
  $res = $query->execute()->fetchAll();

  $data = array();
  foreach($res as $val) {
    $val->country = isset($countries[$val->country]) ? $countries[$val->country] : $val->country;
    $data[$val->country] = $val;
  }
  sort($data);
  return $data;
}

function adsw_dash_get_month_impress($date = REQUEST_TIME) {
  global $user;

  $first_day = date('Y-m-01', $date);
  $last_day = date('Y-m-t', $date);

  $query = db_select('ad_stat', 'stat');
  $query->addExpression('sum(impress)', 'sum');
  $query->condition('date', array($first_day, $last_day), 'BETWEEN');
  $query->condition('user_id', $user->uid);
  $res = $query->execute()->fetchAssoc();

  return $res['sum'];
}

function adsw_dash_get_month_clicks($date = REQUEST_TIME) {
  global $user;

  $first_day = date('Y-m-01', $date);
  $last_day = date('Y-m-t', $date);

  $query = db_select('ad_stat', 'stat');
  $query->addExpression('sum(clicks)', 'sum');
  $query->condition('date', array($first_day, $last_day), 'BETWEEN');
  $query->condition('user_id', $user->uid);
  $res = $query->execute()->fetchAssoc();

  return $res['sum'];
}

function adsw_dash_get_month_revenue($date = REQUEST_TIME) {
  global $user;

  $first_day = date('Y-m-01', $date);
  $last_day = date('Y-m-t', $date);

  $query = db_select('ad_stat', 'stat');
  $query->addExpression('sum(earning)', 'sum');
  $query->condition('date', array($first_day, $last_day), 'BETWEEN');
  $query->condition('user_id', $user->uid);
  $res = $query->execute()->fetchAssoc();

  return $res['sum'];
}
